services:
  compile:
    container_name: compile
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./documentation:/workdir/dist
      - ./tasks:/workdir/tasks
      - ./documentation:/documentation
      - ./.git:/workdir/.git

volumes:
  miktex-packages:
    driver: local