services:
  compile:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tasks:/tasks
      - ./documentation:/documentation


volumes:
  miktex-packages:
    driver: local