name: "Compile files + create version"

on:
  push:
    branches:
      - master

jobs:
  compile-latex-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install TeX distribution
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-basic
            babel
            babel-german
            fontenc
            ucs
            graphicx
            hyperref
            etoolbox
      - name: Compile files
        run: |
          chmod +x ./compile-files.sh
          ./compile-files.sh ./tasks ./documentation
      - name: Create artifacts
        uses: actions/upload-artifact@master
        with:
          name: documentation
          path: |
            ./documentation
  

  create-zip-file:
    needs: compile-latex-files
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: documentation
          path: artifacts/documentation
      - name: Create zip file
        run: |
          zip -r documentation.zip artifacts/documentation
      - name: Create artifacts
        uses: actions/upload-artifact@master
        with:
          name: documentation-zipped
          path: documentation.zip


  create-version:
    needs: create-zip-file
    runs-on: ubuntu-latest
    steps:
      - name: Setup NPM
        uses: actions/setup-node@master
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/gitlab @semantic-release/git
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: documentation-zipped
          path: documentation.zip
      - name: Create version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release